# NumPy Exercise

Creating Arrays.
Numpy Arrays can be created from Lists.
Create Numpy arrays from the lists below:

In [1]:
a = [1,2,3,4,5,6,7,8,9,10]
b = ["Hello","Data","Science"]
c = [True,False,True]
d = [1,3,True,"Hello"]


Remember that NumPy arrays are Homogenious in nature , ie, they can only contain one type of data. Explain what happens in the case of d above

# NumPy arrays can be created in other ways too as shown below

In [2]:
import numpy as np
#creating arrays
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
#creating a matrix with a predefined value
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [5]:
#create an array with a set sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
#create an array of even space between the given range of values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
#create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# NumPy Array Indexing

In [8]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

Get the value at index zero

Get the fifth value

Get the last value

Get the second last value

In [9]:
np_2d = np.array([
    [3, 7, 5, 5],
    [0, 1, 5, 9],
    [3, 0, 5, 0]
])
np_2d

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

Return value at the intersection of the 1st row and 2nd column

Return 3rd row and last value from the 3rd column

Replace value at 0,0 index with 12