# NumPy Exercise

In [1]:
import numpy as np

Creating Arrays.
Numpy Arrays can be created from Lists.
Create Numpy arrays from the lists below:

In [2]:
a = [1,2,3,4,5,6,7,8,9,10]
b = ["Hello","Data","Science"]
c = [True,False,True]
d = [1,3,True,"Hello"]

In [3]:
a_array = np.array(a)
print(a_array)
b_array = np.array(b)
print(b_array)
c_array = np.array(c)
print(c_array)
d_array = np.array(d)
print(d_array)

[ 1  2  3  4  5  6  7  8  9 10]
['Hello' 'Data' 'Science']
[ True False  True]
['1' '3' 'True' 'Hello']


Remember that NumPy arrays are Homogenious in nature , ie, they can only contain one type of data. Explain what happens in the case of d above

In [19]:
# At which indices are the numbers less than or equal to 3?
a_array <= 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [22]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = np.array(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


# NumPy arrays can be created in other ways too as shown below

In [4]:
#creating arrays
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
#creating a matrix with a predefined value
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [7]:
#create an array with a set sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
#create an array of even space between the given range of values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
#create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# NumPy Array Indexing

In [10]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [11]:
# Get the value at index zero

x1[0]

4

In [12]:
# Get the fifth value
x1[4]

8

In [13]:
# Get the last value
x1[-1]

4

In [14]:
# Get the second last value
x1[-2]

8

In [15]:
np_2d = np.array([
    [3, 7, 5, 5],
    [0, 1, 5, 9],
    [3, 0, 5, 0]
])
np_2d

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [16]:
# Return value at the intersection of the 1st row and 2nd column
np_2d[0,1]

7

In [17]:
# Return 3rd row and last value from the 3rd column
np_2d[2,-1]

0

In [18]:
# Replace value at 0,0 index with 12
np_2d[0,0] = 12
np_2d

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])